#PASILLO_DID = "HA_PASSI"
#CUARTO_OESTE_DID = "A2"
#SALON_DID = "A5"
HEATER_DID = "HA_HEATER_DID"
HEATER_PROTOCOL = "HA_HEATER_PROTOCOL_X10"
HEATER_API = "HA_HEATER_API"

HEATER_USERNAME = "HA_HEATER_USERNAME"
HEATER_PASSWORD = "HA_HEATER_PASSWORD"

HEATER_MARGIN = HA_HEATER_MARGIN
HEATER_INCREMENT = HA_HEATER_INCREMENT

MINUTES_AFTER_SUNRISE_FOR_DAY = 60
MINUTES_AFTER_SUNSET_FOR_DAY = 80

LIST_THERMOMETERS_API = "HA_TERMOMETER_SERVER/thermostat/temperatures?"
#TEMPERATURES_API = "HA_TERMOMETER_SERVER/thermometer/temperature_api/thermometers"

FLAME_STATS = HA_FLAME_STATS_ENABLE
FLAME_STATS_PATH = "HA_FLAME_STATS_PATH"
FLAME_STATS_DATE_FORMAT = "%d.%m.%Y %H:%M:%S"